import Link from 'next/link';
import { Calculator, CircleCheck, Network } from 'lucide-react';
import { CompatibilityChecker, LossCalculator, ReadinessCheck, RoiCalculator } from '@/components/activation-tools';
import { PageHeading, FinalCTA } from '@/components/sections';
import { JsonLd } from '@/components/seo';
import { SeoBlock } from '@/components/seo-block';
import { resourcesFaq } from '@/lib/seo-content';

export const metadata={title:'Калькулятор ROI AI-агента та втрат у продажах',description:'Оцініть втрати в переписках, ROI AI-агента, готовність даних і сумісність каналу до пілоту.',alternates:{canonical:'/resursy'}};
export default function ResourcesPage(){return <main id="main"><JsonLd faq={resourcesFaq} path="/resursy" title="Інструменти"/><div className="container"><PageHeading title="Перевірте гіпотезу до запуску" description="Інструменти не зберігають введені дані та не дають фінансових гарантій. Вони допомагають підготувати осмислену розмову про пілот."/><section className="resource-intro"><article><Calculator size={24}/><h2>Оцінки, а не обіцянки</h2><p>Калькулятори показують діапазон для перевірки вашої економіки.</p></article><article><CircleCheck size={24}/><h2>Готовність даних</h2><p>Зрозумійте, чого бракує для безпечного старту.</p></article><article><Network size={24}/><h2>Статус інтеграцій</h2><p>Пілот, узгодження або кастомна перевірка — без псевдоточності.</p></article></section><div className="tool-stack"><LossCalculator/><RoiCalculator/><ReadinessCheck/><CompatibilityChecker/></div><p className="resources-cta">Потрібно розібрати результат під ваш бізнес? <Link href="/start?plan=demo">Подайтеся на пілот</Link>.</p><SeoBlock title="Калькулятор ROI AI-агента та підготовка до пілоту" paragraphs={['Калькулятор втрат у продажах і ROI AI-агента допомагає сформулювати гіпотезу: де команда витрачає час на переписки та який сценарій варто перевірити першим.','Результати не є фінансовою обіцянкою. Їх варто звірити з реальними зверненнями, правилами каналу та роботою менеджерів під час пілоту.']} links={[{href:'/ai-agent-dlya-prodazhiv',label:'AI-агент для продажів',description:'Як агент працює у діалогах.'},{href:'/integratsii',label:'Статуси інтеграцій',description:'Оберіть канал для перевірки.'},{href:'/rishennia/ecommerce',label:'AI для інтернет-магазину',description:'Сценарій для товарних запитів.'},{href:'/rishennia/poslugy',label:'AI для послуг',description:'Сценарій первинної кваліфікації.'},{href:'/keisy',label:'Як вимірюємо кейси',description:'Метрики пілоту без умовних цифр.'},{href:'/tarify',label:'Тарифи AI-продавця',description:'Формати після перевірки цінності.'}]} faq={resourcesFaq}/></div><FinalCTA/></main>}
