import type {Metadata} from 'next';
import Link from 'next/link';
import {ArrowUpRight,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {JsonLd} from '@/components/seo';
import {FinalCTA} from '@/components/sections';

export const metadata:Metadata={title:'AI-агент для продажів',description:'AI-агент для продажів відповідає клієнтам у месенджерах, кваліфікує ліди, працює із запереченнями та передає гарячі діалоги менеджеру.',alternates:{canonical:'/ai-agent-dlya-prodazhiv'}};
const benefits=['Відповідає клієнтам у Telegram, Instagram, Facebook, WhatsApp і на сайті','Працює з базою знань про ваш продукт, послуги та ціни','Ставить уточнювальні питання і кваліфікує звернення','Передає складні та гарячі діалоги менеджеру з повним контекстом','Записує клієнтів на зустріч і нагадує про наступний крок'];

export default function Page(){return <main id="main"><JsonLd path="/ai-agent-dlya-prodazhiv" title="AI-агент для продажів"/><div className="container"><div className="page-heading"><nav aria-label="Хлібні крихти" className="breadcrumbs"><Link href="/">Головна</Link><span>/</span><span aria-current="page">AI-агент для продажів</span></nav><h1>AI-агент для продажів, який відповідає клієнтам 24/7</h1><p>AI-продавець веде переписку, допомагає клієнту зробити наступний крок і не залишає заявку без відповіді.</p></div><section className="two-columns seo-intro"><div><span className="section-label">Що це таке</span><h2>Ваш продавець у кожному діалозі</h2></div><div className="difference-copy"><p>AI-агент для продажів працює у вхідних повідомленнях замість менеджера, але діє за логікою вашого відділу продажів.</p><p>Він відповідає природною мовою, використовує інформацію про ваш бізнес, працює із запереченнями, збирає контакти та передає менеджеру підготовлений діалог.</p></div></section><section className="section feature-section"><div className="container"><div className="section-intro"><span className="section-label">Можливості</span><h2>Від першого питання до наступного кроку</h2></div><ul className="check-list seo-benefits">{benefits.map(item=><li key={item}><Check size={18}/>{item}</li>)}</ul></div></section><section className="section container"><div className="section-intro"><span className="section-label">Як це працює</span><h2>Агент підлаштовується під процес вашого бізнесу</h2></div><div className="difference-grid"><article><h3>1. Вивчає продукт</h3><p>Ви передаєте прайс, опис послуг, відповіді на часті питання або посилання на сайт.</p></article><article><h3>2. Веде діалог</h3><p>Агент уточнює потребу, відповідає на питання, працює із запереченнями та пропонує наступний крок.</p></article><article><h3>3. Передає результат</h3><p>Гарячий клієнт, контакт і контекст розмови переходять менеджеру або в календар.</p></article></div><Button asChild><Link href="/start?plan=demo">Податися на пілот <ArrowUpRight size={18}/></Link></Button></section></div><FinalCTA/></main>}
