import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Check, MessageCircleMore, UserRoundCheck } from 'lucide-react';
import { PageHeading, FinalCTA } from '@/components/sections';
import { JsonLd } from '@/components/seo';

const solutions={
  ecommerce:{title:'AI-продавець для інтернет-магазину',description:'Допомагає розібрати типове питання про товар, доставку або підбір і передає складні ситуації менеджеру.',goal:'Швидше відповідати на повторні запити, не обіцяючи наявність чи доставку без перевірки.',flow:['Клієнт описує товар або задачу.','Агент уточнює ключові параметри й працює лише з погодженою базою знань.','Питання про нестандартну знижку, наявність або оплату передаються менеджеру.'],limits:['Не вигадує залишки, строки доставки чи умови повернення.','Не приймає платіжні дані в demo та без погодженого платіжного процесу.']},
  poslugy:{title:'AI-агент для послуг і запису',description:'Допомагає з первинною кваліфікацією та підготовкою запису, коли правила послуги й роль менеджера визначені заздалегідь.',goal:'Не залишати звернення без відповіді та швидше збирати контекст до розмови з командою.',flow:['Клієнт пояснює потребу та бажаний час.','Агент уточнює послугу, формат і важливі обмеження.','Підтвердження слоту й нестандартні питання передаються людині або погодженому календарю.'],limits:['Не підтверджує запис без підключеного та перевіреного календаря.','Не дає медичних, юридичних чи фінансових порад.']},
  b2b:{title:'AI-кваліфікація B2B-лідів',description:'Збирає контекст про задачу, канали й обсяг звернень, щоб менеджер отримав підготовлений запит.',goal:'Зменшити ручну роботу з первинними питаннями без втрати важливого контексту.',flow:['Лід описує бізнес-задачу.','Агент ставить короткі уточнення про процес, обсяг і бажаний результат.','Менеджер отримує контекст і бере на себе комерційні умови, інтеграції та винятки.'],limits:['Не обіцяє інтеграцію чи термін без технічної перевірки.','Не створює комерційну пропозицію без погоджених даних.']},
} as const;
export function generateStaticParams(){return Object.keys(solutions).map((type)=>({type}));}
export async function generateMetadata({params}:{params:Promise<{type:string}>}){const {type}=await params;const item=solutions[type as keyof typeof solutions];return item?{title:item.title,description:item.description,alternates:{canonical:`/rishennia/${type}`}}:{title:'Рішення не знайдено'};}
export default async function SolutionPage({params}:{params:Promise<{type:string}>}){const {type}=await params;const item=solutions[type as keyof typeof solutions];if(!item)return notFound();return <main id="main"><JsonLd path={`/rishennia/${type}`} title={item.title}/><div className="container"><PageHeading title={item.title} description={item.description}/><section className="solution-hero"><div><span className="section-label">Задача</span><h2>{item.goal}</h2></div><div className="solution-pilot"><MessageCircleMore size={26}/><strong>Починаємо з одного сценарію</strong><p>Перед запуском визначаємо, на які питання агент відповідає, які дані використовує та коли залучає менеджера.</p></div></section><section className="section two-columns"><div><span className="section-label">Сценарій пілоту</span><h2>Як перевіряємо цінність</h2></div><ol className="numbered-list">{item.flow.map((step)=><li key={step}>{step}</li>)}</ol></section><section className="limits-panel"><UserRoundCheck size={25}/><div><h2>Межі, які не обходять</h2><ul className="check-list">{item.limits.map((limit)=><li key={limit}><Check size={18}/>{limit}</li>)}</ul></div></section><div className="solution-links"><Link href="/rishennia/ecommerce">E-commerce</Link><Link href="/rishennia/poslugy">Послуги</Link><Link href="/rishennia/b2b">B2B</Link></div></div><FinalCTA/></main>}
