import { notFound } from 'next/navigation';
import Link from 'next/link';
import { Check, ShieldCheck } from 'lucide-react';
import { integrationCatalog } from '@/lib/content';
import { PageHeading, FinalCTA } from '@/components/sections';
import { JsonLd } from '@/components/seo';

export function generateStaticParams(){return integrationCatalog.map(({slug})=>({channel:slug}));}
export async function generateMetadata({params}:{params:Promise<{channel:string}>}){const {channel}=await params;const item=integrationCatalog.find((entry)=>entry.slug===channel);return item?{title:`${item.name}: підключення AI-агента`,description:item.description,alternates:{canonical:`/integratsii/${item.slug}`}}:{title:'Інтеграцію не знайдено'};}
export default async function ChannelPage({params}:{params:Promise<{channel:string}>}){const {channel}=await params;const item=integrationCatalog.find((entry)=>entry.slug===channel);if(!item)return notFound();return <main id="main"><JsonLd path={`/integratsii/${item.slug}`} title={item.name}/><div className="container"><PageHeading title={`${item.name}: спочатку перевірка, потім підключення`} description={item.description}/><section className="two-columns detail-panel"><div><span className={`status-badge ${item.status==='Пілот'?'pilot':''}`}>{item.status}</span><h2>Що перевіряємо на старті</h2></div><div><ul className="check-list">{item.requirements.map((requirement)=><li key={requirement}><Check size={18}/>{requirement}</li>)}</ul><div className="inline-note"><ShieldCheck size={22}/><p>Не передавайте ключі, паролі чи конфіденційні дані через форму. Доступи погоджуються лише після технічного контакту й фіксації сценарію.</p></div></div></section><section className="section evidence-panel"><span className="section-label">Порядок роботи</span><h2>Малий контрольований пілот</h2><ol className="numbered-list"><li>Уточнюємо ціль діалогу та межі відповідей.</li><li>Перевіряємо доступи, політики каналу й дані, які передаються.</li><li>Тестуємо з командою до ввімкнення реального трафіку.</li><li>Фіксуємо, коли агент передає діалог менеджеру.</li></ol><Link className="button button-primary" href="/start?plan=demo">Обговорити пілот</Link></section></div><FinalCTA/></main>}
