import Link from 'next/link';
import type {Metadata} from 'next';
import {ArrowUpRight,Play,Check,Clock3,ShieldCheck,MessagesSquare} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {ChatMessages} from '@/components/ui/chat-messages';
import {PainSection,FeaturesSection,HowSection,DashboardSection,DifferenceSection,TrustSection,FinalCTA,SalesSystemCTA} from '@/components/sections';
import {DemoAgent,SecurityPromise} from '@/components/activation-tools';
import {Pricing} from '@/components/pricing';
import {FAQ} from '@/components/faq';
import {faq} from '@/lib/content';
import {getMarket} from '@/lib/market';
import {JsonLd} from '@/components/seo';
export const metadata:Metadata={title:'AI-продавець для бізнесу - AI для продажів 24/7',description:'AI-продавець для бізнесу веде переписки, кваліфікує ліди та передає складні діалоги менеджеру. Почніть із безпечного пілоту.',alternates:{canonical:'/'}};
export default async function Home(){const market=await getMarket();return <main id="main"><JsonLd faq={faq}/><section className="hero container"><div className="hero-copy"><div className="eyebrow"><span/> AI-агенти для продажів у переписках</div><h1>Не втрачайте клієнтів, поки команда не в мережі</h1><p>AI-продавець відповідає на типові запити 24/7, з’ясовує потребу й передає менеджеру розмову з готовим контекстом. Почніть із короткої консультації: підберемо один реалістичний сценарій саме для вашого бізнесу.</p><div className="actions hero-actions"><Button asChild><Link href="/demo">Записатися на консультацію <ArrowUpRight size={18}/></Link></Button><Button asChild variant="ghost"><a href="#live-demo"><Play size={16}/> Спершу подивитися демо</a></Button></div><div className="hero-reassurance"><span><Clock3 size={15}/> 15 хвилин, без зобов’язань</span><span><ShieldCheck size={15}/> Без картки й паролів</span></div><div className="hero-proof"><div className="hero-proof-icon"><MessagesSquare size={18}/></div><p><strong>Практика продажів, вбудована в діалог</strong><span>130+ проєктів · 30+ ніш · 3 600+ годин консалтингу</span></p></div></div><div className="hero-product"><ChatMessages/></div></section><div className="channel-strip container"><span>Працює зі сценаріями для каналів</span><strong>Telegram</strong><strong>Instagram</strong><strong>Messenger</strong><strong>WhatsApp</strong><strong>Чат на сайті</strong></div><DemoAgent/><PainSection/><FeaturesSection/><HowSection/><DashboardSection/><SecurityPromise/><DifferenceSection/><TrustSection/><section className="section pricing-section container"><div className="section-intro"><span className="section-label">Тарифи</span><h2>Продавець під ваш масштаб</h2><p>Підбираємо тариф після перевірки каналу, сценарію та обсягу звернень на пілоті.</p></div><Pricing initialMarket={market}/></section><section className="section faq-section container" id="faq"><div><span className="section-label">Відповіді</span><h2>Питання перед першим діалогом</h2><p>Залишилось своє?<br/><a href="https://t.me/tripailo_ads">Напишіть нам у Telegram ↗</a></p></div><FAQ items={faq}/></section><FinalCTA/><SalesSystemCTA/></main>}
