import Link from 'next/link';
import {MessageCircle,BookOpen,Layers,UserRoundCheck,CalendarDays,RefreshCw,ArrowUpRight,MessageSquare,LayoutDashboard,Tag,ChartNoAxesCombined,Database} from 'lucide-react';
import {features,steps,dashboard,differences,pains} from '@/lib/content';
import {Button} from '@/components/ui/button';
import {NumberTicker} from '@/components/ui/number-ticker';
const featureIcons=[MessageCircle,BookOpen,Layers,UserRoundCheck,CalendarDays,RefreshCw];
export function PainSection(){return <section className="section container"><div className="section-intro"><span className="section-label">Знайомі ситуації</span><h2>Скільки клієнтів ви втратили, поки писали цей рядок</h2></div><div className="pain-grid">{pains.map((p,i)=><article key={p}><span className="quote-mark" aria-hidden="true">«</span><p>{p}</p><span className="pain-context">{['Після робочого дня','У кількох месенджерах','На повторних питаннях','Без обліку звернень'][i]}</span></article>)}</div><p className="closing-line">Кожен непрочитаний діалог це гроші, які пішли до конкурента. AI-агент закриває цей розрив за секунди.</p></section>}
export function FeaturesSection(){return <section className="section feature-section"><div className="container"><div className="section-intro"><span className="section-label">Що робить агент</span><h2>Не автовідповідач. Продавець</h2><p>Агент веде діалог, а не віддає готові відповіді зі списку.</p></div><div className="bento-grid">{features.map(([title,body],i)=>{const Icon=featureIcons[i];return <article className={'feature-card feature-'+i} key={title}><Icon size={27} strokeWidth={1.4}/><h3>{title}</h3><p>{body}</p>{i===0&&<div className="conversation-flow"><span>Запит клієнта</span><div/><span>Уточнення потреби</span><div/><span>Наступний крок <ArrowUpRight size={15}/></span></div>}</article>})}</div><div className="center-link"><Link href="/mozhlyvosti">Усі можливості агента ↗</Link></div></div></section>}
export function HowSection(){return <section id="how" className="section container"><div className="section-intro"><span className="section-label">Запуск</span><h2>Від «нічого немає» до першого діалогу за один вечір</h2></div><ol className="steps-grid">{steps.map(([title,body],i)=><li key={title}><span className="step-number">0{i+1}</span><h3>{title}</h3><p>{body}</p></li>)}</ol><p className="closing-line">Базове налаштування займає від 15 хвилин. Глибока база знань, кілька сценаріїв і інтеграції: до одного робочого дня.</p></section>}
export function DashboardSection(){return <section className="section dashboard-section"><div className="container"><div className="section-intro"><span className="section-label">Робочий простір</span><h2>Видно все, що відбувається в чатах прямо зараз</h2><p>Ніяких здогадок. Дані, на яких можна ухвалювати рішення.</p></div><div className="dashboard-preview"><aside aria-hidden="true"><span className="dashboard-brand">мп</span>{[LayoutDashboard,MessageSquare,Database,BookOpen,Tag].map((I,i)=><I key={i} size={19}/>)}</aside><div className="dashboard-main"><div className="dashboard-title"><strong>Огляд діалогів</strong><span className="tag">Макет для демонстрації</span></div><div className="dashboard-stat-grid">{['Нові ліди','Активні діалоги','Передано менеджеру'].map(label=><div key={label}><span>{label}</span><strong>···</strong><small>Дані вашого бізнесу</small></div>)}</div><div className="dashboard-columns"><div><div className="mock-table-title">Єдина база звернень</div>{[['Telegram','Питання про послугу'],['Instagram','Запис на зустріч'],['Віджет','Консультація']].map(([c,t])=><div className="mock-row" key={c}><span className="mock-avatar"><MessageCircle size={15}/></span><div><strong>{t}</strong><small>{c}</small></div><span className="mock-status">Приклад</span></div>)}</div><div className="dashboard-empty"><ChartNoAxesCombined size={38} strokeWidth={1}/><strong>Активність за каналами</strong><p>Тут відображатиметься статистика звернень</p></div></div><p className="preview-caption">Схема можливостей. Реальні скріншоти кабінету додамо після погодження.</p></div></div><div className="dashboard-features">{dashboard.map(([t,b])=><article key={t}><h3>{t}</h3><p>{b}</p></article>)}</div></div></section>}
export function DifferenceSection(){return <section className="section difference-section"><div className="container"><div className="two-columns"><div><span className="section-label">Експертиза за технологією</span><h2>Різниця між ботом і продавцем це той, хто його навчив</h2></div><div className="difference-copy"><p>Агента можна купити де завгодно. Питання в тому, чи вміє він продавати.</p><p>Ми будуємо відділи продажів з 2023 року: 130+ проєктів, 30+ ніш, 3 600+ годин консалтингу. Ті самі скрипти, та сама робота із запереченнями і та сама логіка кваліфікації, які ми ставимо живим менеджерам, лягають в основу агента.</p><p>Тому агент не просто відповідає. Він кваліфікує, веде до наступного кроку і передає менеджеру рівно тоді, коли це потрібно.</p></div></div><div className="difference-grid">{differences.map(([t,b])=><article key={t}><h3>{t}</h3><p>{b}</p></article>)}</div><Button asChild variant="outline"><a href="https://ministrysale.com/ai-agent">Дізнатись про повний супровід <ArrowUpRight size={18}/></a></Button></div></section>}
export function TrustSection(){const stats=[{value:130,suffix:'+',label:'реалізованих проєктів'},{value:30,suffix:'+',label:'ніш'},{value:3600,suffix:'+',label:'годин консалтингу'},{value:2023,suffix:'',label:'рік реєстрації торгової марки'}];return <section className="section trust-section container"><div className="trust-grid">{stats.map(({value,suffix,label},index)=><div key={label}><strong><NumberTicker value={value} delay={index*.08}/>{suffix}</strong><span>{label}</span></div>)}</div><p>Компанія «Міністерство з Продажів». Будуємо системні відділи продажів для українського і європейського МСБ.</p></section>}
export function FinalCTA(){return <section className="section container final-cta"><span className="section-label">Ваш наступний крок</span><h2>Перестаньте втрачати клієнтів у ночі та вихідні</h2><p>Почніть із короткого пілоту: перевіримо один сценарій, роль менеджера та готовність каналу до запуску.</p><div className="actions"><Button asChild><Link href="/start?plan=demo">Податися на пілот <ArrowUpRight size={18}/></Link></Button><Button asChild variant="outline"><Link href="/demo">Обговорити demo, 15 хвилин</Link></Button></div></section>}
export function SalesSystemCTA(){return <section className="section container sales-system-cta"><span className="section-label">Повна система продажів</span><h2>Потрібно більше, ніж AI-продавець у переписці?</h2><p>«Міністерство з Продажів» допомагає побудувати весь відділ продажів: CRM, скрипти, KPI, навчання менеджерів і контроль якості.</p><Button asChild variant="outline"><a href="https://ministrysale.com" target="_blank" rel="noopener noreferrer">Перейти на сайт Міністерства з Продажів <ArrowUpRight size={18}/></a></Button></section>}
export function PageHeading({title,description}:{title:string;description:string}){return <div className="page-heading"><nav aria-label="Хлібні крихти" className="breadcrumbs"><Link href="/">Головна</Link><span>/</span><span aria-current="page">{title}</span></nav><h1>{title}</h1><p>{description}</p></div>}
