'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import * as Dialog from '@radix-ui/react-dialog';
import {Menu,X} from 'lucide-react';
import {useState,useEffect} from 'react';
import {Button} from '@/components/ui/button';
export const links=[['Можливості','/mozhlyvosti'],['Інтеграції','/integratsii'],['Тарифи','/tarify'],['FAQ','/#faq']];
export function Brand(){return <Link href="/" className="brand" aria-label="Міністерство з Продажів, головна"><span className="brand-logo-frame"><img src="/logo-white.png" alt="Міністерство з Продажів" className="brand-logo"/></span><span className="brand-product">AI-агенти для продажів</span></Link>}
export function Header(){const [open,setOpen]=useState(false);const [scrolled,setScrolled]=useState(false);const path=usePathname();useEffect(()=>{setOpen(false)},[path]);useEffect(()=>{const handler=()=>setScrolled(window.scrollY>20);handler();window.addEventListener('scroll',handler,{passive:true});return()=>window.removeEventListener('scroll',handler)},[]);return <header className={scrolled?'header scrolled':'header'}><div className="container header-inner"><Brand/><nav className="desktop-nav" aria-label="Основне меню">{links.map(([label,url])=><Link href={url} key={url} aria-current={path===url?'page':undefined}>{label}</Link>)}</nav><Button asChild className="header-cta"><Link href="/start?plan=demo">Спробувати безкоштовно</Link></Button><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button className="menu-toggle" aria-label="Відкрити меню"><Menu/></button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="mobile-menu"><Dialog.Title>Меню</Dialog.Title><Dialog.Description className="sr-only">Навігація сайтом</Dialog.Description><Dialog.Close className="close-button" aria-label="Закрити меню"><X/></Dialog.Close><Brand/><nav>{links.map(([label,url])=><Link href={url} key={url} onClick={()=>setOpen(false)}>{label}</Link>)}<Link href="/demo" onClick={()=>setOpen(false)}>Записатись на демо</Link></nav></Dialog.Content></Dialog.Portal></Dialog.Root></div></header>}
const legal=[['Публічна оферта','/oferta'],['Політика конфіденційності','/privacy-policy'],['Політика cookie','/cookie-policy'],['Умови обробки даних','/dpa'],['Повернення коштів','/refund-policy']];
export function Footer(){return <footer className="footer"><div className="container"><div className="footer-grid"><div><Brand/><p>Продажі продовжуються.<br/>Навіть коли робочий день закінчився.</p></div><div><h3>Продукт</h3>{links.slice(0,4).map(([l,u])=><Link href={u} key={u}>{l}</Link>)}<Link href="/demo">Демо</Link></div><div><h3>Компанія</h3><a href="https://ministrysale.com" target="_blank" rel="noopener noreferrer">Міністерство з Продажів ↗</a><Link href="/kontakty">Контакти</Link><a href="mailto:info@ministrysale.org">info@ministrysale.org</a><a href="https://t.me/tripailo_ads">Telegram</a></div><div><h3>Правове</h3>{legal.map(([l,u])=><Link href={u} key={u}>{l}</Link>)}</div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Міністерство з Продажів</span><span>ФОП Проценко Марта Олександрівна</span><button onClick={()=>window.dispatchEvent(new Event('open-cookie-settings'))}>Налаштування cookie</button></div></div></footer>}
