import Link from 'next/link';
import {Send,Instagram,MessageCircle,Phone,PanelBottom,CalendarDays,Webhook,Code2} from 'lucide-react';
import {PageHeading,FinalCTA} from '@/components/sections';
import {integrationCatalog} from '@/lib/content';
import {JsonLd} from '@/components/seo';
import {SeoBlock} from '@/components/seo-block';
import {integrationsFaq} from '@/lib/seo-content';
const icons=[Send,Instagram,MessageCircle,Phone,PanelBottom,CalendarDays,Webhook,Code2];
export const metadata={title:'Інтеграції AI-агента: Telegram, Instagram, CRM',description:'Статуси інтеграцій AI-агента: Telegram, Instagram, WhatsApp, чат-віджет, Google Calendar, CRM, вебхуки та API.',alternates:{canonical:'/integratsii'}};
export default function Page(){return <main id="main"><JsonLd faq={integrationsFaq} path="/integratsii" title="Інтеграції"/><div className="container"><PageHeading title="Підключення починається зі статусу, а не обіцянки" description="Показуємо, що можна перевіряти на пілоті, а що потребує окремого погодження. Це допомагає не запускати неперевірені сценарії на реальному трафіку."/><div className="integration-grid">{integrationCatalog.map((item,i)=>{const Icon=icons[i]||Code2;return <article key={item.slug}><div className="integration-top"><Icon size={30} strokeWidth={1.4}/><span className={`tag integration-status ${item.status==='Пілот'?'pilot':''}`}>{item.status}</span></div><span className="integration-kind">{item.kind}</span><h2>{item.name}</h2><p>{item.description}</p><Link className="text-link" href={`/integratsii/${item.slug}`}>Вимоги до пілоту <span aria-hidden="true">→</span></Link></article>})}</div><div className="inline-callout"><div><h3>Потрібне підключення до вашої CRM?</h3><p>Перевіримо сумісність, формат подій і сценарій передачі даних до того, як підключати доступи.</p></div><Link href="/start?plan=business" className="button button-outline">Обговорити інтеграцію</Link></div><SeoBlock title="Інтеграції AI-агента для продажів" paragraphs={['Інтеграція AI-агента починається не з передачі доступів, а з перевірки каналу, політик платформи, сценарію діалогу та даних, які дійсно потрібні команді.', 'Окремі сторінки інтеграцій показують вимоги до Telegram, Instagram Direct, WhatsApp Business, чат-віджета, Google Calendar і CRM.']} links={[{href:'/integratsii/telegram',label:'AI-агент у Telegram',description:'Пілот для власного бота бізнесу.'},{href:'/integratsii/instagram',label:'AI для Instagram Direct',description:'Перевірка Meta-акаунта та handoff.'},{href:'/integratsii/calendar',label:'Google Calendar',description:'Правила слотів і запису на зустріч.'},{href:'/integratsii/crm',label:'CRM, вебхуки та API',description:'Формат даних і технічна сумісність.'},{href:'/bezpeka',label:'Безпека підключення',description:'Межі доступу та робота з даними.'},{href:'/resursy',label:'Перевірити сумісність',description:'Інструмент підготовки до пілоту.'}]} faq={integrationsFaq}/></div><FinalCTA/></main>}
